# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'potHoleCity' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.5'
  pod 'SimpleButton', '~> 3.0'
  pod 'SpreadButton', '~> 0.2'
  pod 'lottie-ios'

end
